// Code generated by Kitex v0.13.1. DO NOT EDIT.

package zkserver_operations

import (
	api "Wx_MQ/kitex_gen/api"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ProGetBro": kitex.NewMethodInfo(
		proGetBroHandler,
		newZKServer_OperationsProGetBroArgs,
		newZKServer_OperationsProGetBroResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ConGetBro": kitex.NewMethodInfo(
		conGetBroHandler,
		newZKServer_OperationsConGetBroArgs,
		newZKServer_OperationsConGetBroResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"sub": kitex.NewMethodInfo(
		subHandler,
		newZKServer_OperationsSubArgs,
		newZKServer_OperationsSubResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BroInfo": kitex.NewMethodInfo(
		broInfoHandler,
		newZKServer_OperationsBroInfoArgs,
		newZKServer_OperationsBroInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BroGetssign": kitex.NewMethodInfo(
		broGetssignHandler,
		newZKServer_OperationsBroGetssignArgs,
		newZKServer_OperationsBroGetssignResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateTopic": kitex.NewMethodInfo(
		createTopicHandler,
		newZKServer_OperationsCreateTopicArgs,
		newZKServer_OperationsCreateTopicResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreatePartition": kitex.NewMethodInfo(
		createPartitionHandler,
		newZKServer_OperationsCreatePartitionArgs,
		newZKServer_OperationsCreatePartitionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	zKServer_OperationsServiceInfo                = NewServiceInfo()
	zKServer_OperationsServiceInfoForClient       = NewServiceInfoForClient()
	zKServer_OperationsServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return zKServer_OperationsServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return zKServer_OperationsServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return zKServer_OperationsServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ZKServer_Operations"
	handlerType := (*api.ZKServer_Operations)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func proGetBroHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ZKServer_OperationsProGetBroArgs)
	realResult := result.(*api.ZKServer_OperationsProGetBroResult)
	success, err := handler.(api.ZKServer_Operations).ProGetBro(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newZKServer_OperationsProGetBroArgs() interface{} {
	return api.NewZKServer_OperationsProGetBroArgs()
}

func newZKServer_OperationsProGetBroResult() interface{} {
	return api.NewZKServer_OperationsProGetBroResult()
}

func conGetBroHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ZKServer_OperationsConGetBroArgs)
	realResult := result.(*api.ZKServer_OperationsConGetBroResult)
	success, err := handler.(api.ZKServer_Operations).ConGetBro(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newZKServer_OperationsConGetBroArgs() interface{} {
	return api.NewZKServer_OperationsConGetBroArgs()
}

func newZKServer_OperationsConGetBroResult() interface{} {
	return api.NewZKServer_OperationsConGetBroResult()
}

func subHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ZKServer_OperationsSubArgs)
	realResult := result.(*api.ZKServer_OperationsSubResult)
	success, err := handler.(api.ZKServer_Operations).Sub(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newZKServer_OperationsSubArgs() interface{} {
	return api.NewZKServer_OperationsSubArgs()
}

func newZKServer_OperationsSubResult() interface{} {
	return api.NewZKServer_OperationsSubResult()
}

func broInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ZKServer_OperationsBroInfoArgs)
	realResult := result.(*api.ZKServer_OperationsBroInfoResult)
	success, err := handler.(api.ZKServer_Operations).BroInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newZKServer_OperationsBroInfoArgs() interface{} {
	return api.NewZKServer_OperationsBroInfoArgs()
}

func newZKServer_OperationsBroInfoResult() interface{} {
	return api.NewZKServer_OperationsBroInfoResult()
}

func broGetssignHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ZKServer_OperationsBroGetssignArgs)
	realResult := result.(*api.ZKServer_OperationsBroGetssignResult)
	success, err := handler.(api.ZKServer_Operations).BroGetssign(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newZKServer_OperationsBroGetssignArgs() interface{} {
	return api.NewZKServer_OperationsBroGetssignArgs()
}

func newZKServer_OperationsBroGetssignResult() interface{} {
	return api.NewZKServer_OperationsBroGetssignResult()
}

func createTopicHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ZKServer_OperationsCreateTopicArgs)
	realResult := result.(*api.ZKServer_OperationsCreateTopicResult)
	success, err := handler.(api.ZKServer_Operations).CreateTopic(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newZKServer_OperationsCreateTopicArgs() interface{} {
	return api.NewZKServer_OperationsCreateTopicArgs()
}

func newZKServer_OperationsCreateTopicResult() interface{} {
	return api.NewZKServer_OperationsCreateTopicResult()
}

func createPartitionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ZKServer_OperationsCreatePartitionArgs)
	realResult := result.(*api.ZKServer_OperationsCreatePartitionResult)
	success, err := handler.(api.ZKServer_Operations).CreatePartition(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newZKServer_OperationsCreatePartitionArgs() interface{} {
	return api.NewZKServer_OperationsCreatePartitionArgs()
}

func newZKServer_OperationsCreatePartitionResult() interface{} {
	return api.NewZKServer_OperationsCreatePartitionResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ProGetBro(ctx context.Context, req *api.ProGetBroRequest) (r *api.ProGetBroResponse, err error) {
	var _args api.ZKServer_OperationsProGetBroArgs
	_args.Req = req
	var _result api.ZKServer_OperationsProGetBroResult
	if err = p.c.Call(ctx, "ProGetBro", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConGetBro(ctx context.Context, req *api.ConGetBroRequest) (r *api.ConGetBroResponse, err error) {
	var _args api.ZKServer_OperationsConGetBroArgs
	_args.Req = req
	var _result api.ZKServer_OperationsConGetBroResult
	if err = p.c.Call(ctx, "ConGetBro", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Sub(ctx context.Context, req *api.SubRequest) (r *api.SubResponse, err error) {
	var _args api.ZKServer_OperationsSubArgs
	_args.Req = req
	var _result api.ZKServer_OperationsSubResult
	if err = p.c.Call(ctx, "sub", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BroInfo(ctx context.Context, req *api.BroInfoRequest) (r *api.BroInfoResponse, err error) {
	var _args api.ZKServer_OperationsBroInfoArgs
	_args.Req = req
	var _result api.ZKServer_OperationsBroInfoResult
	if err = p.c.Call(ctx, "BroInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BroGetssign(ctx context.Context, req *api.BroGetAssignRequest) (r *api.BroGetAssignResponse, err error) {
	var _args api.ZKServer_OperationsBroGetssignArgs
	_args.Req = req
	var _result api.ZKServer_OperationsBroGetssignResult
	if err = p.c.Call(ctx, "BroGetssign", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateTopic(ctx context.Context, req *api.CreateTopicRequest) (r *api.CreateTopicResponse, err error) {
	var _args api.ZKServer_OperationsCreateTopicArgs
	_args.Req = req
	var _result api.ZKServer_OperationsCreateTopicResult
	if err = p.c.Call(ctx, "CreateTopic", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreatePartition(ctx context.Context, req *api.CreatePartitionRequest) (r *api.CreatePartitionResponse, err error) {
	var _args api.ZKServer_OperationsCreatePartitionArgs
	_args.Req = req
	var _result api.ZKServer_OperationsCreatePartitionResult
	if err = p.c.Call(ctx, "CreatePartition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
