// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package api

import (
	"context"
	"fmt"
)

type PushRequest struct {
	ProducerId string `thrift:"producerId,1" frugal:"1,default,string" json:"producerId"`
	Topic      string `thrift:"topic,2" frugal:"2,default,string" json:"topic"`
	Key        string `thrift:"key,3" frugal:"3,default,string" json:"key"`
	Message    string `thrift:"message,4" frugal:"4,default,string" json:"message"`
}

func NewPushRequest() *PushRequest {
	return &PushRequest{}
}

func (p *PushRequest) InitDefault() {
}

func (p *PushRequest) GetProducerId() (v string) {
	return p.ProducerId
}

func (p *PushRequest) GetTopic() (v string) {
	return p.Topic
}

func (p *PushRequest) GetKey() (v string) {
	return p.Key
}

func (p *PushRequest) GetMessage() (v string) {
	return p.Message
}
func (p *PushRequest) SetProducerId(val string) {
	p.ProducerId = val
}
func (p *PushRequest) SetTopic(val string) {
	p.Topic = val
}
func (p *PushRequest) SetKey(val string) {
	p.Key = val
}
func (p *PushRequest) SetMessage(val string) {
	p.Message = val
}

func (p *PushRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PushRequest(%+v)", *p)
}

var fieldIDToName_PushRequest = map[int16]string{
	1: "producerId",
	2: "topic",
	3: "key",
	4: "message",
}

type PushResponse struct {
	Ret bool `thrift:"ret,1" frugal:"1,default,bool" json:"ret"`
}

func NewPushResponse() *PushResponse {
	return &PushResponse{}
}

func (p *PushResponse) InitDefault() {
}

func (p *PushResponse) GetRet() (v bool) {
	return p.Ret
}
func (p *PushResponse) SetRet(val bool) {
	p.Ret = val
}

func (p *PushResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PushResponse(%+v)", *p)
}

var fieldIDToName_PushResponse = map[int16]string{
	1: "ret",
}

type PullRequest struct {
	ConsumerId string `thrift:"consumerId,1" frugal:"1,default,string" json:"consumerId"`
	Topic      string `thrift:"topic,2" frugal:"2,default,string" json:"topic"`
	Key        string `thrift:"key,3" frugal:"3,default,string" json:"key"`
}

func NewPullRequest() *PullRequest {
	return &PullRequest{}
}

func (p *PullRequest) InitDefault() {
}

func (p *PullRequest) GetConsumerId() (v string) {
	return p.ConsumerId
}

func (p *PullRequest) GetTopic() (v string) {
	return p.Topic
}

func (p *PullRequest) GetKey() (v string) {
	return p.Key
}
func (p *PullRequest) SetConsumerId(val string) {
	p.ConsumerId = val
}
func (p *PullRequest) SetTopic(val string) {
	p.Topic = val
}
func (p *PullRequest) SetKey(val string) {
	p.Key = val
}

func (p *PullRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PullRequest(%+v)", *p)
}

var fieldIDToName_PullRequest = map[int16]string{
	1: "consumerId",
	2: "topic",
	3: "key",
}

type PullResponse struct {
	Message string `thrift:"message,1" frugal:"1,default,string" json:"message"`
}

func NewPullResponse() *PullResponse {
	return &PullResponse{}
}

func (p *PullResponse) InitDefault() {
}

func (p *PullResponse) GetMessage() (v string) {
	return p.Message
}
func (p *PullResponse) SetMessage(val string) {
	p.Message = val
}

func (p *PullResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PullResponse(%+v)", *p)
}

var fieldIDToName_PullResponse = map[int16]string{
	1: "message",
}

type InfoRequest struct {
	IpPort string `thrift:"ip_port,1" frugal:"1,default,string" json:"ip_port"`
}

func NewInfoRequest() *InfoRequest {
	return &InfoRequest{}
}

func (p *InfoRequest) InitDefault() {
}

func (p *InfoRequest) GetIpPort() (v string) {
	return p.IpPort
}
func (p *InfoRequest) SetIpPort(val string) {
	p.IpPort = val
}

func (p *InfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InfoRequest(%+v)", *p)
}

var fieldIDToName_InfoRequest = map[int16]string{
	1: "ip_port",
}

type InfoResponse struct {
	Ret bool `thrift:"ret,1" frugal:"1,default,bool" json:"ret"`
}

func NewInfoResponse() *InfoResponse {
	return &InfoResponse{}
}

func (p *InfoResponse) InitDefault() {
}

func (p *InfoResponse) GetRet() (v bool) {
	return p.Ret
}
func (p *InfoResponse) SetRet(val bool) {
	p.Ret = val
}

func (p *InfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InfoResponse(%+v)", *p)
}

var fieldIDToName_InfoResponse = map[int16]string{
	1: "ret",
}

type InfoGetRequest struct {
	Cli_Name       string `thrift:"cli_Name,1" frugal:"1,default,string" json:"cli_Name"`
	Topic_Name     string `thrift:"topic_Name,2" frugal:"2,default,string" json:"topic_Name"`
	Partition_Name string `thrift:"partition_Name,3" frugal:"3,default,string" json:"partition_Name"`
	Offset         int64  `thrift:"offset,4" frugal:"4,default,i64" json:"offset"`
	Option         int8   `thrift:"option,5" frugal:"5,default,i8" json:"option"`
}

func NewInfoGetRequest() *InfoGetRequest {
	return &InfoGetRequest{}
}

func (p *InfoGetRequest) InitDefault() {
}

func (p *InfoGetRequest) GetCli_Name() (v string) {
	return p.Cli_Name
}

func (p *InfoGetRequest) GetTopic_Name() (v string) {
	return p.Topic_Name
}

func (p *InfoGetRequest) GetPartition_Name() (v string) {
	return p.Partition_Name
}

func (p *InfoGetRequest) GetOffset() (v int64) {
	return p.Offset
}

func (p *InfoGetRequest) GetOption() (v int8) {
	return p.Option
}
func (p *InfoGetRequest) SetCli_Name(val string) {
	p.Cli_Name = val
}
func (p *InfoGetRequest) SetTopic_Name(val string) {
	p.Topic_Name = val
}
func (p *InfoGetRequest) SetPartition_Name(val string) {
	p.Partition_Name = val
}
func (p *InfoGetRequest) SetOffset(val int64) {
	p.Offset = val
}
func (p *InfoGetRequest) SetOption(val int8) {
	p.Option = val
}

func (p *InfoGetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InfoGetRequest(%+v)", *p)
}

var fieldIDToName_InfoGetRequest = map[int16]string{
	1: "cli_Name",
	2: "topic_Name",
	3: "partition_Name",
	4: "offset",
	5: "option",
}

type InfoGetResponse struct {
	Ret bool `thrift:"ret,1" frugal:"1,default,bool" json:"ret"`
}

func NewInfoGetResponse() *InfoGetResponse {
	return &InfoGetResponse{}
}

func (p *InfoGetResponse) InitDefault() {
}

func (p *InfoGetResponse) GetRet() (v bool) {
	return p.Ret
}
func (p *InfoGetResponse) SetRet(val bool) {
	p.Ret = val
}

func (p *InfoGetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InfoGetResponse(%+v)", *p)
}

var fieldIDToName_InfoGetResponse = map[int16]string{
	1: "ret",
}

type SubRequest struct {
	Consumer string `thrift:"consumer,1" frugal:"1,default,string" json:"consumer"`
	Topic    string `thrift:"topic,2" frugal:"2,default,string" json:"topic"`
	Key      string `thrift:"key,3" frugal:"3,default,string" json:"key"`
	Option   int8   `thrift:"option,4" frugal:"4,default,i8" json:"option"`
}

func NewSubRequest() *SubRequest {
	return &SubRequest{}
}

func (p *SubRequest) InitDefault() {
}

func (p *SubRequest) GetConsumer() (v string) {
	return p.Consumer
}

func (p *SubRequest) GetTopic() (v string) {
	return p.Topic
}

func (p *SubRequest) GetKey() (v string) {
	return p.Key
}

func (p *SubRequest) GetOption() (v int8) {
	return p.Option
}
func (p *SubRequest) SetConsumer(val string) {
	p.Consumer = val
}
func (p *SubRequest) SetTopic(val string) {
	p.Topic = val
}
func (p *SubRequest) SetKey(val string) {
	p.Key = val
}
func (p *SubRequest) SetOption(val int8) {
	p.Option = val
}

func (p *SubRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubRequest(%+v)", *p)
}

var fieldIDToName_SubRequest = map[int16]string{
	1: "consumer",
	2: "topic",
	3: "key",
	4: "option",
}

type SubResponse struct {
	Ret bool `thrift:"ret,1" frugal:"1,default,bool" json:"ret"`
}

func NewSubResponse() *SubResponse {
	return &SubResponse{}
}

func (p *SubResponse) InitDefault() {
}

func (p *SubResponse) GetRet() (v bool) {
	return p.Ret
}
func (p *SubResponse) SetRet(val bool) {
	p.Ret = val
}

func (p *SubResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubResponse(%+v)", *p)
}

var fieldIDToName_SubResponse = map[int16]string{
	1: "ret",
}

type PubRequest struct {
	TopicName     string `thrift:"topic_name,1" frugal:"1,default,string" json:"topic_name"`
	PartitionName string `thrift:"partition_name,2" frugal:"2,default,string" json:"partition_name"`
	StartIndex    int64  `thrift:"start_index,3" frugal:"3,default,i64" json:"start_index"`
	EndIndex      int64  `thrift:"end_index,4" frugal:"4,default,i64" json:"end_index"`
	Msg           []byte `thrift:"msg,5" frugal:"5,default,binary" json:"msg"`
}

func NewPubRequest() *PubRequest {
	return &PubRequest{}
}

func (p *PubRequest) InitDefault() {
}

func (p *PubRequest) GetTopicName() (v string) {
	return p.TopicName
}

func (p *PubRequest) GetPartitionName() (v string) {
	return p.PartitionName
}

func (p *PubRequest) GetStartIndex() (v int64) {
	return p.StartIndex
}

func (p *PubRequest) GetEndIndex() (v int64) {
	return p.EndIndex
}

func (p *PubRequest) GetMsg() (v []byte) {
	return p.Msg
}
func (p *PubRequest) SetTopicName(val string) {
	p.TopicName = val
}
func (p *PubRequest) SetPartitionName(val string) {
	p.PartitionName = val
}
func (p *PubRequest) SetStartIndex(val int64) {
	p.StartIndex = val
}
func (p *PubRequest) SetEndIndex(val int64) {
	p.EndIndex = val
}
func (p *PubRequest) SetMsg(val []byte) {
	p.Msg = val
}

func (p *PubRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PubRequest(%+v)", *p)
}

var fieldIDToName_PubRequest = map[int16]string{
	1: "topic_name",
	2: "partition_name",
	3: "start_index",
	4: "end_index",
	5: "msg",
}

type PubResponse struct {
	Ret bool `thrift:"ret,1" frugal:"1,default,bool" json:"ret"`
}

func NewPubResponse() *PubResponse {
	return &PubResponse{}
}

func (p *PubResponse) InitDefault() {
}

func (p *PubResponse) GetRet() (v bool) {
	return p.Ret
}
func (p *PubResponse) SetRet(val bool) {
	p.Ret = val
}

func (p *PubResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PubResponse(%+v)", *p)
}

var fieldIDToName_PubResponse = map[int16]string{
	1: "ret",
}

type PingpongRequest struct {
	Ping bool `thrift:"ping,1" frugal:"1,default,bool" json:"ping"`
}

func NewPingpongRequest() *PingpongRequest {
	return &PingpongRequest{}
}

func (p *PingpongRequest) InitDefault() {
}

func (p *PingpongRequest) GetPing() (v bool) {
	return p.Ping
}
func (p *PingpongRequest) SetPing(val bool) {
	p.Ping = val
}

func (p *PingpongRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PingpongRequest(%+v)", *p)
}

var fieldIDToName_PingpongRequest = map[int16]string{
	1: "ping",
}

type PingpongResponse struct {
	Pong bool `thrift:"pong,1" frugal:"1,default,bool" json:"pong"`
}

func NewPingpongResponse() *PingpongResponse {
	return &PingpongResponse{}
}

func (p *PingpongResponse) InitDefault() {
}

func (p *PingpongResponse) GetPong() (v bool) {
	return p.Pong
}
func (p *PingpongResponse) SetPong(val bool) {
	p.Pong = val
}

func (p *PingpongResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PingpongResponse(%+v)", *p)
}

var fieldIDToName_PingpongResponse = map[int16]string{
	1: "pong",
}

type BroInfoRequest struct {
	BroName     string `thrift:"bro_name,1" frugal:"1,default,string" json:"bro_name"`
	BroHostPort string `thrift:"bro_host_port,2" frugal:"2,default,string" json:"bro_host_port"`
}

func NewBroInfoRequest() *BroInfoRequest {
	return &BroInfoRequest{}
}

func (p *BroInfoRequest) InitDefault() {
}

func (p *BroInfoRequest) GetBroName() (v string) {
	return p.BroName
}

func (p *BroInfoRequest) GetBroHostPort() (v string) {
	return p.BroHostPort
}
func (p *BroInfoRequest) SetBroName(val string) {
	p.BroName = val
}
func (p *BroInfoRequest) SetBroHostPort(val string) {
	p.BroHostPort = val
}

func (p *BroInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BroInfoRequest(%+v)", *p)
}

var fieldIDToName_BroInfoRequest = map[int16]string{
	1: "bro_name",
	2: "bro_host_port",
}

type BroInfoResponse struct {
	Ret bool `thrift:"ret,1" frugal:"1,default,bool" json:"ret"`
}

func NewBroInfoResponse() *BroInfoResponse {
	return &BroInfoResponse{}
}

func (p *BroInfoResponse) InitDefault() {
}

func (p *BroInfoResponse) GetRet() (v bool) {
	return p.Ret
}
func (p *BroInfoResponse) SetRet(val bool) {
	p.Ret = val
}

func (p *BroInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BroInfoResponse(%+v)", *p)
}

var fieldIDToName_BroInfoResponse = map[int16]string{
	1: "ret",
}

type ProGetBroRequest struct {
	TopicName     string `thrift:"topic_name,1" frugal:"1,default,string" json:"topic_name"`
	PartitionName string `thrift:"partition_name,2" frugal:"2,default,string" json:"partition_name"`
}

func NewProGetBroRequest() *ProGetBroRequest {
	return &ProGetBroRequest{}
}

func (p *ProGetBroRequest) InitDefault() {
}

func (p *ProGetBroRequest) GetTopicName() (v string) {
	return p.TopicName
}

func (p *ProGetBroRequest) GetPartitionName() (v string) {
	return p.PartitionName
}
func (p *ProGetBroRequest) SetTopicName(val string) {
	p.TopicName = val
}
func (p *ProGetBroRequest) SetPartitionName(val string) {
	p.PartitionName = val
}

func (p *ProGetBroRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProGetBroRequest(%+v)", *p)
}

var fieldIDToName_ProGetBroRequest = map[int16]string{
	1: "topic_name",
	2: "partition_name",
}

type ProGetBroResponse struct {
	Ret         bool   `thrift:"ret,1" frugal:"1,default,bool" json:"ret"`
	BroHostPort string `thrift:"bro_host_port,2" frugal:"2,default,string" json:"bro_host_port"`
}

func NewProGetBroResponse() *ProGetBroResponse {
	return &ProGetBroResponse{}
}

func (p *ProGetBroResponse) InitDefault() {
}

func (p *ProGetBroResponse) GetRet() (v bool) {
	return p.Ret
}

func (p *ProGetBroResponse) GetBroHostPort() (v string) {
	return p.BroHostPort
}
func (p *ProGetBroResponse) SetRet(val bool) {
	p.Ret = val
}
func (p *ProGetBroResponse) SetBroHostPort(val string) {
	p.BroHostPort = val
}

func (p *ProGetBroResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProGetBroResponse(%+v)", *p)
}

var fieldIDToName_ProGetBroResponse = map[int16]string{
	1: "ret",
	2: "bro_host_port",
}

type ConGetBroRequest struct {
	TopicName     string `thrift:"topic_name,1" frugal:"1,default,string" json:"topic_name"`
	PartitionName string `thrift:"partition_name,2" frugal:"2,default,string" json:"partition_name"`
	Option        int8   `thrift:"option,3" frugal:"3,default,i8" json:"option"`
}

func NewConGetBroRequest() *ConGetBroRequest {
	return &ConGetBroRequest{}
}

func (p *ConGetBroRequest) InitDefault() {
}

func (p *ConGetBroRequest) GetTopicName() (v string) {
	return p.TopicName
}

func (p *ConGetBroRequest) GetPartitionName() (v string) {
	return p.PartitionName
}

func (p *ConGetBroRequest) GetOption() (v int8) {
	return p.Option
}
func (p *ConGetBroRequest) SetTopicName(val string) {
	p.TopicName = val
}
func (p *ConGetBroRequest) SetPartitionName(val string) {
	p.PartitionName = val
}
func (p *ConGetBroRequest) SetOption(val int8) {
	p.Option = val
}

func (p *ConGetBroRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConGetBroRequest(%+v)", *p)
}

var fieldIDToName_ConGetBroRequest = map[int16]string{
	1: "topic_name",
	2: "partition_name",
	3: "option",
}

type ConGetBroResponse struct {
	Ret   bool   `thrift:"ret,1" frugal:"1,default,bool" json:"ret"`
	Size  int64  `thrift:"size,2" frugal:"2,default,i64" json:"size"`
	Bros  []byte `thrift:"bros,3" frugal:"3,default,binary" json:"bros"`
	Parts []byte `thrift:"parts,4" frugal:"4,default,binary" json:"parts"`
}

func NewConGetBroResponse() *ConGetBroResponse {
	return &ConGetBroResponse{}
}

func (p *ConGetBroResponse) InitDefault() {
}

func (p *ConGetBroResponse) GetRet() (v bool) {
	return p.Ret
}

func (p *ConGetBroResponse) GetSize() (v int64) {
	return p.Size
}

func (p *ConGetBroResponse) GetBros() (v []byte) {
	return p.Bros
}

func (p *ConGetBroResponse) GetParts() (v []byte) {
	return p.Parts
}
func (p *ConGetBroResponse) SetRet(val bool) {
	p.Ret = val
}
func (p *ConGetBroResponse) SetSize(val int64) {
	p.Size = val
}
func (p *ConGetBroResponse) SetBros(val []byte) {
	p.Bros = val
}
func (p *ConGetBroResponse) SetParts(val []byte) {
	p.Parts = val
}

func (p *ConGetBroResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConGetBroResponse(%+v)", *p)
}

var fieldIDToName_ConGetBroResponse = map[int16]string{
	1: "ret",
	2: "size",
	3: "bros",
	4: "parts",
}

type BroGetAssignRequest struct {
	Brokerpower []byte `thrift:"brokerpower,1" frugal:"1,default,binary" json:"brokerpower"`
}

func NewBroGetAssignRequest() *BroGetAssignRequest {
	return &BroGetAssignRequest{}
}

func (p *BroGetAssignRequest) InitDefault() {
}

func (p *BroGetAssignRequest) GetBrokerpower() (v []byte) {
	return p.Brokerpower
}
func (p *BroGetAssignRequest) SetBrokerpower(val []byte) {
	p.Brokerpower = val
}

func (p *BroGetAssignRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BroGetAssignRequest(%+v)", *p)
}

var fieldIDToName_BroGetAssignRequest = map[int16]string{
	1: "brokerpower",
}

type BroGetAssignResponse struct {
	Ret        bool   `thrift:"ret,1" frugal:"1,default,bool" json:"ret"`
	Assignment []byte `thrift:"assignment,2" frugal:"2,default,binary" json:"assignment"`
}

func NewBroGetAssignResponse() *BroGetAssignResponse {
	return &BroGetAssignResponse{}
}

func (p *BroGetAssignResponse) InitDefault() {
}

func (p *BroGetAssignResponse) GetRet() (v bool) {
	return p.Ret
}

func (p *BroGetAssignResponse) GetAssignment() (v []byte) {
	return p.Assignment
}
func (p *BroGetAssignResponse) SetRet(val bool) {
	p.Ret = val
}
func (p *BroGetAssignResponse) SetAssignment(val []byte) {
	p.Assignment = val
}

func (p *BroGetAssignResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BroGetAssignResponse(%+v)", *p)
}

var fieldIDToName_BroGetAssignResponse = map[int16]string{
	1: "ret",
	2: "assignment",
}

type Server_Operations interface {
	Push(ctx context.Context, req *PushRequest) (r *PushResponse, err error)

	Pull(ctx context.Context, req *PullRequest) (r *PullResponse, err error)

	Info(ctx context.Context, req *InfoRequest) (r *InfoResponse, err error)

	Sub(ctx context.Context, req *SubRequest) (r *SubResponse, err error)

	StarttoGet(ctx context.Context, req *InfoGetRequest) (r *InfoGetResponse, err error)
}

type Server_OperationsPushArgs struct {
	Req *PushRequest `thrift:"req,1" frugal:"1,default,PushRequest" json:"req"`
}

func NewServer_OperationsPushArgs() *Server_OperationsPushArgs {
	return &Server_OperationsPushArgs{}
}

func (p *Server_OperationsPushArgs) InitDefault() {
}

var Server_OperationsPushArgs_Req_DEFAULT *PushRequest

func (p *Server_OperationsPushArgs) GetReq() (v *PushRequest) {
	if !p.IsSetReq() {
		return Server_OperationsPushArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *Server_OperationsPushArgs) SetReq(val *PushRequest) {
	p.Req = val
}

func (p *Server_OperationsPushArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *Server_OperationsPushArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Server_OperationsPushArgs(%+v)", *p)
}

var fieldIDToName_Server_OperationsPushArgs = map[int16]string{
	1: "req",
}

type Server_OperationsPushResult struct {
	Success *PushResponse `thrift:"success,0,optional" frugal:"0,optional,PushResponse" json:"success,omitempty"`
}

func NewServer_OperationsPushResult() *Server_OperationsPushResult {
	return &Server_OperationsPushResult{}
}

func (p *Server_OperationsPushResult) InitDefault() {
}

var Server_OperationsPushResult_Success_DEFAULT *PushResponse

func (p *Server_OperationsPushResult) GetSuccess() (v *PushResponse) {
	if !p.IsSetSuccess() {
		return Server_OperationsPushResult_Success_DEFAULT
	}
	return p.Success
}
func (p *Server_OperationsPushResult) SetSuccess(x interface{}) {
	p.Success = x.(*PushResponse)
}

func (p *Server_OperationsPushResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *Server_OperationsPushResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Server_OperationsPushResult(%+v)", *p)
}

var fieldIDToName_Server_OperationsPushResult = map[int16]string{
	0: "success",
}

type Server_OperationsPullArgs struct {
	Req *PullRequest `thrift:"req,1" frugal:"1,default,PullRequest" json:"req"`
}

func NewServer_OperationsPullArgs() *Server_OperationsPullArgs {
	return &Server_OperationsPullArgs{}
}

func (p *Server_OperationsPullArgs) InitDefault() {
}

var Server_OperationsPullArgs_Req_DEFAULT *PullRequest

func (p *Server_OperationsPullArgs) GetReq() (v *PullRequest) {
	if !p.IsSetReq() {
		return Server_OperationsPullArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *Server_OperationsPullArgs) SetReq(val *PullRequest) {
	p.Req = val
}

func (p *Server_OperationsPullArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *Server_OperationsPullArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Server_OperationsPullArgs(%+v)", *p)
}

var fieldIDToName_Server_OperationsPullArgs = map[int16]string{
	1: "req",
}

type Server_OperationsPullResult struct {
	Success *PullResponse `thrift:"success,0,optional" frugal:"0,optional,PullResponse" json:"success,omitempty"`
}

func NewServer_OperationsPullResult() *Server_OperationsPullResult {
	return &Server_OperationsPullResult{}
}

func (p *Server_OperationsPullResult) InitDefault() {
}

var Server_OperationsPullResult_Success_DEFAULT *PullResponse

func (p *Server_OperationsPullResult) GetSuccess() (v *PullResponse) {
	if !p.IsSetSuccess() {
		return Server_OperationsPullResult_Success_DEFAULT
	}
	return p.Success
}
func (p *Server_OperationsPullResult) SetSuccess(x interface{}) {
	p.Success = x.(*PullResponse)
}

func (p *Server_OperationsPullResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *Server_OperationsPullResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Server_OperationsPullResult(%+v)", *p)
}

var fieldIDToName_Server_OperationsPullResult = map[int16]string{
	0: "success",
}

type Server_OperationsInfoArgs struct {
	Req *InfoRequest `thrift:"req,1" frugal:"1,default,InfoRequest" json:"req"`
}

func NewServer_OperationsInfoArgs() *Server_OperationsInfoArgs {
	return &Server_OperationsInfoArgs{}
}

func (p *Server_OperationsInfoArgs) InitDefault() {
}

var Server_OperationsInfoArgs_Req_DEFAULT *InfoRequest

func (p *Server_OperationsInfoArgs) GetReq() (v *InfoRequest) {
	if !p.IsSetReq() {
		return Server_OperationsInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *Server_OperationsInfoArgs) SetReq(val *InfoRequest) {
	p.Req = val
}

func (p *Server_OperationsInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *Server_OperationsInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Server_OperationsInfoArgs(%+v)", *p)
}

var fieldIDToName_Server_OperationsInfoArgs = map[int16]string{
	1: "req",
}

type Server_OperationsInfoResult struct {
	Success *InfoResponse `thrift:"success,0,optional" frugal:"0,optional,InfoResponse" json:"success,omitempty"`
}

func NewServer_OperationsInfoResult() *Server_OperationsInfoResult {
	return &Server_OperationsInfoResult{}
}

func (p *Server_OperationsInfoResult) InitDefault() {
}

var Server_OperationsInfoResult_Success_DEFAULT *InfoResponse

func (p *Server_OperationsInfoResult) GetSuccess() (v *InfoResponse) {
	if !p.IsSetSuccess() {
		return Server_OperationsInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *Server_OperationsInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*InfoResponse)
}

func (p *Server_OperationsInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *Server_OperationsInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Server_OperationsInfoResult(%+v)", *p)
}

var fieldIDToName_Server_OperationsInfoResult = map[int16]string{
	0: "success",
}

type Server_OperationsSubArgs struct {
	Req *SubRequest `thrift:"req,1" frugal:"1,default,SubRequest" json:"req"`
}

func NewServer_OperationsSubArgs() *Server_OperationsSubArgs {
	return &Server_OperationsSubArgs{}
}

func (p *Server_OperationsSubArgs) InitDefault() {
}

var Server_OperationsSubArgs_Req_DEFAULT *SubRequest

func (p *Server_OperationsSubArgs) GetReq() (v *SubRequest) {
	if !p.IsSetReq() {
		return Server_OperationsSubArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *Server_OperationsSubArgs) SetReq(val *SubRequest) {
	p.Req = val
}

func (p *Server_OperationsSubArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *Server_OperationsSubArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Server_OperationsSubArgs(%+v)", *p)
}

var fieldIDToName_Server_OperationsSubArgs = map[int16]string{
	1: "req",
}

type Server_OperationsSubResult struct {
	Success *SubResponse `thrift:"success,0,optional" frugal:"0,optional,SubResponse" json:"success,omitempty"`
}

func NewServer_OperationsSubResult() *Server_OperationsSubResult {
	return &Server_OperationsSubResult{}
}

func (p *Server_OperationsSubResult) InitDefault() {
}

var Server_OperationsSubResult_Success_DEFAULT *SubResponse

func (p *Server_OperationsSubResult) GetSuccess() (v *SubResponse) {
	if !p.IsSetSuccess() {
		return Server_OperationsSubResult_Success_DEFAULT
	}
	return p.Success
}
func (p *Server_OperationsSubResult) SetSuccess(x interface{}) {
	p.Success = x.(*SubResponse)
}

func (p *Server_OperationsSubResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *Server_OperationsSubResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Server_OperationsSubResult(%+v)", *p)
}

var fieldIDToName_Server_OperationsSubResult = map[int16]string{
	0: "success",
}

type Server_OperationsStarttoGetArgs struct {
	Req *InfoGetRequest `thrift:"req,1" frugal:"1,default,InfoGetRequest" json:"req"`
}

func NewServer_OperationsStarttoGetArgs() *Server_OperationsStarttoGetArgs {
	return &Server_OperationsStarttoGetArgs{}
}

func (p *Server_OperationsStarttoGetArgs) InitDefault() {
}

var Server_OperationsStarttoGetArgs_Req_DEFAULT *InfoGetRequest

func (p *Server_OperationsStarttoGetArgs) GetReq() (v *InfoGetRequest) {
	if !p.IsSetReq() {
		return Server_OperationsStarttoGetArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *Server_OperationsStarttoGetArgs) SetReq(val *InfoGetRequest) {
	p.Req = val
}

func (p *Server_OperationsStarttoGetArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *Server_OperationsStarttoGetArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Server_OperationsStarttoGetArgs(%+v)", *p)
}

var fieldIDToName_Server_OperationsStarttoGetArgs = map[int16]string{
	1: "req",
}

type Server_OperationsStarttoGetResult struct {
	Success *InfoGetResponse `thrift:"success,0,optional" frugal:"0,optional,InfoGetResponse" json:"success,omitempty"`
}

func NewServer_OperationsStarttoGetResult() *Server_OperationsStarttoGetResult {
	return &Server_OperationsStarttoGetResult{}
}

func (p *Server_OperationsStarttoGetResult) InitDefault() {
}

var Server_OperationsStarttoGetResult_Success_DEFAULT *InfoGetResponse

func (p *Server_OperationsStarttoGetResult) GetSuccess() (v *InfoGetResponse) {
	if !p.IsSetSuccess() {
		return Server_OperationsStarttoGetResult_Success_DEFAULT
	}
	return p.Success
}
func (p *Server_OperationsStarttoGetResult) SetSuccess(x interface{}) {
	p.Success = x.(*InfoGetResponse)
}

func (p *Server_OperationsStarttoGetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *Server_OperationsStarttoGetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Server_OperationsStarttoGetResult(%+v)", *p)
}

var fieldIDToName_Server_OperationsStarttoGetResult = map[int16]string{
	0: "success",
}

type Client_Operations interface {
	Pub(ctx context.Context, req *PubRequest) (r *PubResponse, err error)

	Pingpong(ctx context.Context, req *PingpongRequest) (r *PingpongResponse, err error)
}

type Client_OperationsPubArgs struct {
	Req *PubRequest `thrift:"req,1" frugal:"1,default,PubRequest" json:"req"`
}

func NewClient_OperationsPubArgs() *Client_OperationsPubArgs {
	return &Client_OperationsPubArgs{}
}

func (p *Client_OperationsPubArgs) InitDefault() {
}

var Client_OperationsPubArgs_Req_DEFAULT *PubRequest

func (p *Client_OperationsPubArgs) GetReq() (v *PubRequest) {
	if !p.IsSetReq() {
		return Client_OperationsPubArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *Client_OperationsPubArgs) SetReq(val *PubRequest) {
	p.Req = val
}

func (p *Client_OperationsPubArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *Client_OperationsPubArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Client_OperationsPubArgs(%+v)", *p)
}

var fieldIDToName_Client_OperationsPubArgs = map[int16]string{
	1: "req",
}

type Client_OperationsPubResult struct {
	Success *PubResponse `thrift:"success,0,optional" frugal:"0,optional,PubResponse" json:"success,omitempty"`
}

func NewClient_OperationsPubResult() *Client_OperationsPubResult {
	return &Client_OperationsPubResult{}
}

func (p *Client_OperationsPubResult) InitDefault() {
}

var Client_OperationsPubResult_Success_DEFAULT *PubResponse

func (p *Client_OperationsPubResult) GetSuccess() (v *PubResponse) {
	if !p.IsSetSuccess() {
		return Client_OperationsPubResult_Success_DEFAULT
	}
	return p.Success
}
func (p *Client_OperationsPubResult) SetSuccess(x interface{}) {
	p.Success = x.(*PubResponse)
}

func (p *Client_OperationsPubResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *Client_OperationsPubResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Client_OperationsPubResult(%+v)", *p)
}

var fieldIDToName_Client_OperationsPubResult = map[int16]string{
	0: "success",
}

type Client_OperationsPingpongArgs struct {
	Req *PingpongRequest `thrift:"req,1" frugal:"1,default,PingpongRequest" json:"req"`
}

func NewClient_OperationsPingpongArgs() *Client_OperationsPingpongArgs {
	return &Client_OperationsPingpongArgs{}
}

func (p *Client_OperationsPingpongArgs) InitDefault() {
}

var Client_OperationsPingpongArgs_Req_DEFAULT *PingpongRequest

func (p *Client_OperationsPingpongArgs) GetReq() (v *PingpongRequest) {
	if !p.IsSetReq() {
		return Client_OperationsPingpongArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *Client_OperationsPingpongArgs) SetReq(val *PingpongRequest) {
	p.Req = val
}

func (p *Client_OperationsPingpongArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *Client_OperationsPingpongArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Client_OperationsPingpongArgs(%+v)", *p)
}

var fieldIDToName_Client_OperationsPingpongArgs = map[int16]string{
	1: "req",
}

type Client_OperationsPingpongResult struct {
	Success *PingpongResponse `thrift:"success,0,optional" frugal:"0,optional,PingpongResponse" json:"success,omitempty"`
}

func NewClient_OperationsPingpongResult() *Client_OperationsPingpongResult {
	return &Client_OperationsPingpongResult{}
}

func (p *Client_OperationsPingpongResult) InitDefault() {
}

var Client_OperationsPingpongResult_Success_DEFAULT *PingpongResponse

func (p *Client_OperationsPingpongResult) GetSuccess() (v *PingpongResponse) {
	if !p.IsSetSuccess() {
		return Client_OperationsPingpongResult_Success_DEFAULT
	}
	return p.Success
}
func (p *Client_OperationsPingpongResult) SetSuccess(x interface{}) {
	p.Success = x.(*PingpongResponse)
}

func (p *Client_OperationsPingpongResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *Client_OperationsPingpongResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Client_OperationsPingpongResult(%+v)", *p)
}

var fieldIDToName_Client_OperationsPingpongResult = map[int16]string{
	0: "success",
}

type ZKServer_Operations interface {
	BroInfo(ctx context.Context, req *BroInfoRequest) (r *BroInfoResponse, err error)

	ProGetBro(ctx context.Context, req *ProGetBroRequest) (r *ProGetBroResponse, err error)

	ConGetBro(ctx context.Context, req *ConGetBroRequest) (r *ConGetBroResponse, err error)

	BroGetssign(ctx context.Context, req *BroGetAssignRequest) (r *BroGetAssignResponse, err error)
}

type ZKServer_OperationsBroInfoArgs struct {
	Req *BroInfoRequest `thrift:"req,1" frugal:"1,default,BroInfoRequest" json:"req"`
}

func NewZKServer_OperationsBroInfoArgs() *ZKServer_OperationsBroInfoArgs {
	return &ZKServer_OperationsBroInfoArgs{}
}

func (p *ZKServer_OperationsBroInfoArgs) InitDefault() {
}

var ZKServer_OperationsBroInfoArgs_Req_DEFAULT *BroInfoRequest

func (p *ZKServer_OperationsBroInfoArgs) GetReq() (v *BroInfoRequest) {
	if !p.IsSetReq() {
		return ZKServer_OperationsBroInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ZKServer_OperationsBroInfoArgs) SetReq(val *BroInfoRequest) {
	p.Req = val
}

func (p *ZKServer_OperationsBroInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ZKServer_OperationsBroInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ZKServer_OperationsBroInfoArgs(%+v)", *p)
}

var fieldIDToName_ZKServer_OperationsBroInfoArgs = map[int16]string{
	1: "req",
}

type ZKServer_OperationsBroInfoResult struct {
	Success *BroInfoResponse `thrift:"success,0,optional" frugal:"0,optional,BroInfoResponse" json:"success,omitempty"`
}

func NewZKServer_OperationsBroInfoResult() *ZKServer_OperationsBroInfoResult {
	return &ZKServer_OperationsBroInfoResult{}
}

func (p *ZKServer_OperationsBroInfoResult) InitDefault() {
}

var ZKServer_OperationsBroInfoResult_Success_DEFAULT *BroInfoResponse

func (p *ZKServer_OperationsBroInfoResult) GetSuccess() (v *BroInfoResponse) {
	if !p.IsSetSuccess() {
		return ZKServer_OperationsBroInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ZKServer_OperationsBroInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*BroInfoResponse)
}

func (p *ZKServer_OperationsBroInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ZKServer_OperationsBroInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ZKServer_OperationsBroInfoResult(%+v)", *p)
}

var fieldIDToName_ZKServer_OperationsBroInfoResult = map[int16]string{
	0: "success",
}

type ZKServer_OperationsProGetBroArgs struct {
	Req *ProGetBroRequest `thrift:"req,1" frugal:"1,default,ProGetBroRequest" json:"req"`
}

func NewZKServer_OperationsProGetBroArgs() *ZKServer_OperationsProGetBroArgs {
	return &ZKServer_OperationsProGetBroArgs{}
}

func (p *ZKServer_OperationsProGetBroArgs) InitDefault() {
}

var ZKServer_OperationsProGetBroArgs_Req_DEFAULT *ProGetBroRequest

func (p *ZKServer_OperationsProGetBroArgs) GetReq() (v *ProGetBroRequest) {
	if !p.IsSetReq() {
		return ZKServer_OperationsProGetBroArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ZKServer_OperationsProGetBroArgs) SetReq(val *ProGetBroRequest) {
	p.Req = val
}

func (p *ZKServer_OperationsProGetBroArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ZKServer_OperationsProGetBroArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ZKServer_OperationsProGetBroArgs(%+v)", *p)
}

var fieldIDToName_ZKServer_OperationsProGetBroArgs = map[int16]string{
	1: "req",
}

type ZKServer_OperationsProGetBroResult struct {
	Success *ProGetBroResponse `thrift:"success,0,optional" frugal:"0,optional,ProGetBroResponse" json:"success,omitempty"`
}

func NewZKServer_OperationsProGetBroResult() *ZKServer_OperationsProGetBroResult {
	return &ZKServer_OperationsProGetBroResult{}
}

func (p *ZKServer_OperationsProGetBroResult) InitDefault() {
}

var ZKServer_OperationsProGetBroResult_Success_DEFAULT *ProGetBroResponse

func (p *ZKServer_OperationsProGetBroResult) GetSuccess() (v *ProGetBroResponse) {
	if !p.IsSetSuccess() {
		return ZKServer_OperationsProGetBroResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ZKServer_OperationsProGetBroResult) SetSuccess(x interface{}) {
	p.Success = x.(*ProGetBroResponse)
}

func (p *ZKServer_OperationsProGetBroResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ZKServer_OperationsProGetBroResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ZKServer_OperationsProGetBroResult(%+v)", *p)
}

var fieldIDToName_ZKServer_OperationsProGetBroResult = map[int16]string{
	0: "success",
}

type ZKServer_OperationsConGetBroArgs struct {
	Req *ConGetBroRequest `thrift:"req,1" frugal:"1,default,ConGetBroRequest" json:"req"`
}

func NewZKServer_OperationsConGetBroArgs() *ZKServer_OperationsConGetBroArgs {
	return &ZKServer_OperationsConGetBroArgs{}
}

func (p *ZKServer_OperationsConGetBroArgs) InitDefault() {
}

var ZKServer_OperationsConGetBroArgs_Req_DEFAULT *ConGetBroRequest

func (p *ZKServer_OperationsConGetBroArgs) GetReq() (v *ConGetBroRequest) {
	if !p.IsSetReq() {
		return ZKServer_OperationsConGetBroArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ZKServer_OperationsConGetBroArgs) SetReq(val *ConGetBroRequest) {
	p.Req = val
}

func (p *ZKServer_OperationsConGetBroArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ZKServer_OperationsConGetBroArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ZKServer_OperationsConGetBroArgs(%+v)", *p)
}

var fieldIDToName_ZKServer_OperationsConGetBroArgs = map[int16]string{
	1: "req",
}

type ZKServer_OperationsConGetBroResult struct {
	Success *ConGetBroResponse `thrift:"success,0,optional" frugal:"0,optional,ConGetBroResponse" json:"success,omitempty"`
}

func NewZKServer_OperationsConGetBroResult() *ZKServer_OperationsConGetBroResult {
	return &ZKServer_OperationsConGetBroResult{}
}

func (p *ZKServer_OperationsConGetBroResult) InitDefault() {
}

var ZKServer_OperationsConGetBroResult_Success_DEFAULT *ConGetBroResponse

func (p *ZKServer_OperationsConGetBroResult) GetSuccess() (v *ConGetBroResponse) {
	if !p.IsSetSuccess() {
		return ZKServer_OperationsConGetBroResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ZKServer_OperationsConGetBroResult) SetSuccess(x interface{}) {
	p.Success = x.(*ConGetBroResponse)
}

func (p *ZKServer_OperationsConGetBroResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ZKServer_OperationsConGetBroResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ZKServer_OperationsConGetBroResult(%+v)", *p)
}

var fieldIDToName_ZKServer_OperationsConGetBroResult = map[int16]string{
	0: "success",
}

type ZKServer_OperationsBroGetssignArgs struct {
	Req *BroGetAssignRequest `thrift:"req,1" frugal:"1,default,BroGetAssignRequest" json:"req"`
}

func NewZKServer_OperationsBroGetssignArgs() *ZKServer_OperationsBroGetssignArgs {
	return &ZKServer_OperationsBroGetssignArgs{}
}

func (p *ZKServer_OperationsBroGetssignArgs) InitDefault() {
}

var ZKServer_OperationsBroGetssignArgs_Req_DEFAULT *BroGetAssignRequest

func (p *ZKServer_OperationsBroGetssignArgs) GetReq() (v *BroGetAssignRequest) {
	if !p.IsSetReq() {
		return ZKServer_OperationsBroGetssignArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ZKServer_OperationsBroGetssignArgs) SetReq(val *BroGetAssignRequest) {
	p.Req = val
}

func (p *ZKServer_OperationsBroGetssignArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ZKServer_OperationsBroGetssignArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ZKServer_OperationsBroGetssignArgs(%+v)", *p)
}

var fieldIDToName_ZKServer_OperationsBroGetssignArgs = map[int16]string{
	1: "req",
}

type ZKServer_OperationsBroGetssignResult struct {
	Success *BroGetAssignResponse `thrift:"success,0,optional" frugal:"0,optional,BroGetAssignResponse" json:"success,omitempty"`
}

func NewZKServer_OperationsBroGetssignResult() *ZKServer_OperationsBroGetssignResult {
	return &ZKServer_OperationsBroGetssignResult{}
}

func (p *ZKServer_OperationsBroGetssignResult) InitDefault() {
}

var ZKServer_OperationsBroGetssignResult_Success_DEFAULT *BroGetAssignResponse

func (p *ZKServer_OperationsBroGetssignResult) GetSuccess() (v *BroGetAssignResponse) {
	if !p.IsSetSuccess() {
		return ZKServer_OperationsBroGetssignResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ZKServer_OperationsBroGetssignResult) SetSuccess(x interface{}) {
	p.Success = x.(*BroGetAssignResponse)
}

func (p *ZKServer_OperationsBroGetssignResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ZKServer_OperationsBroGetssignResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ZKServer_OperationsBroGetssignResult(%+v)", *p)
}

var fieldIDToName_ZKServer_OperationsBroGetssignResult = map[int16]string{
	0: "success",
}
